### ISSUE TITLE
[EROR] (cssharp:PluginManager) Failed to load plugin

### ISSUE THREAD

**Issue by Geant200** [oqyh/cs2-Map-Configs-GoldKingZ#6]
Hello I am using the latest version of the plugin.

```
2024-06-23 16:26:52.652 +02:00 [INFO] (cssharp:PluginContext) Loading plugin Map-Configs-GoldKingZ
2024-06-23 16:26:52.658 +02:00 [EROR] (cssharp:PluginManager) Failed to load plugin from E:\AMPDatastore\Instances\War-TeamFr-ServeurPrincipal01\counter-strike2\730\game\csgo\addons\counterstrikesharp\plugins\Map-Configs-GoldKingZ\Map-Configs-GoldKingZ.dll
System.UnauthorizedAccessException: Access to the path 'E:\AMPDatastore\Instances\War-TeamFr-ServeurPrincipal01\counter-strike2\730\game\csgo\addons\counterstrikesharp\plugins\Map-Configs-GoldKingZ\config\config.json' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at Map_Configs_GoldKingZ.Config.Configs.SaveConfigData(ConfigData configData) in C:\Users\oqyh\Documents\cs2-Map-Configs-GoldKingZ\Config\Configs.cs:line 81
   at Map_Configs_GoldKingZ.Config.Configs.Load(String modulePath) in C:\Users\oqyh\Documents\cs2-Map-Configs-GoldKingZ\Config\Configs.cs:line 67
   at Map_Configs_GoldKingZ.MapConfigsGoldKingZ.Load(Boolean hotReload) in C:\Users\oqyh\Documents\cs2-Map-Configs-GoldKingZ\Map-Configs-GoldKingZ.cs:line 19
   at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
   at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
```

**Comment by oqyh** [comment]
> Hello I am using the latest version of the plugin.
> 
> ```
> 2024-06-23 16:26:52.652 +02:00 [INFO] (cssharp:PluginContext) Loading plugin Map-Configs-GoldKingZ
> 2024-06-23 16:26:52.658 +02:00 [EROR] (cssharp:PluginManager) Failed to load plugin from E:\AMPDatastore\Instances\War-TeamFr-ServeurPrincipal01\counter-strike2\730\game\csgo\addons\counterstrikesharp\plugins\Map-Configs-GoldKingZ\Map-Configs-GoldKingZ.dll
> System.UnauthorizedAccessException: Access to the path 'E:\AMPDatastore\Instances\War-TeamFr-ServeurPrincipal01\counter-strike2\730\game\csgo\addons\counterstrikesharp\plugins\Map-Configs-GoldKingZ\config\config.json' is denied.
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
>    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
>    at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
>    at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
>    at Map_Configs_GoldKingZ.Config.Configs.SaveConfigData(ConfigData configData) in C:\Users\oqyh\Documents\cs2-Map-Configs-GoldKingZ\Config\Configs.cs:line 81
>    at Map_Configs_GoldKingZ.Config.Configs.Load(String modulePath) in C:\Users\oqyh\Documents\cs2-Map-Configs-GoldKingZ\Config\Configs.cs:line 67
>    at Map_Configs_GoldKingZ.MapConfigsGoldKingZ.Load(Boolean hotReload) in C:\Users\oqyh\Documents\cs2-Map-Configs-GoldKingZ\Map-Configs-GoldKingZ.cs:line 19
>    at CounterStrikeSharp.API.Core.Plugin.PluginContext.Load(Boolean hotReload) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/PluginContext.cs:line 218
>    at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.LoadPlugin(String path) in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 125
>    at CounterStrikeSharp.API.Core.Plugin.Host.PluginManager.Load() in /home/runner/work/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/Plugin/Host/PluginManager.cs:line 93
> ```

hello Geant200,

you problem Access config.json denied give permission to read and write (777) to folder 

game\csgo\addons\counterstrikesharp\plugins\ `Map-Configs-GoldKingZ`

if you did restart server

**Comment by Geant200** [comment]
It's fixed thanks ^^.
